kornicameister/dotfiles

.gitmodules
=> Remove omitted powerline module

.installer/install_latest_dev.sh
=> Fix shellcheck in install_latest_dev

.circleci/config.yml
=> Fix checkout submodules

python-system-requirements.txt
This reverts commit fe65b641ff152951f2df06566f7bd8b6447fde79.
=> Revert "Add pipenv"

fzf.settings
- make it more readable
- remove repetitions
- add completion options for fzf
=> Cleanup fzf options

.gitmodules, install.conf.yaml, t.sh
=> Remove "t"

bin/upgrade
Variables for functions ought to be local for them, right?
=> Do not leak variables outside

install, vim/ftplugin/go.vim, vim/plugins.vim
=> goenv meets VIM

vim/plugins.vim
See [here](https://github.com/haya14busa/incsearch.vim) in **README.md** in a section concerning auto disabling that.
=> Updare setup around ncsearch-

bin/upgrade, pkg.install.conf.yaml, zsh/zshrc
=> Revert installing extras in pkgs

.installer/verify_install.sh
=> Drop `tig`

remove.pkgs.txt
=> Add extra packages to remove

zsh/zshrc
=> Remove installing jq via zplugin

.gitmodules, .installer/verify_install.sh, gitignore, install, install.conf.yaml, pkg.install.conf.yaml, vim/plugins.vim, zsh/zprofile, zsh/zshrc
- jenv
- default java, if installed in system
- latest java, as download from **AdoptOpenJDK**
- shell integration
---
Closes: #370
=> Adds Java handling

.installer/verify_install.sh, pkg.install.conf.yaml
=> Add screenfetch

vim/editor.vim, vim/plugins.vim, vimrc
See: https://github.com/axelburks/fzf/pull/43
=> Make FZF float in neovim

bin/upgrade, install, vim/after/ftplugin/elm.vim, vim/plugins.vim
Closes: #206 
Also: https://github.com/pbogut/deoplete-elm/issues/3
=> Use elm_language_server

.gitmodules
=> Use new URL for zplugin (now zinit)

.installer/verify_install.sh, pkg.install.conf.yaml
Should fix build breaking since c55ceedebb71910ee7a92c5be2ea0ef61726953c
=> Fix installing exiftool

zsh/zshrc
=> Change to zdharma/z-p-submods to zinit-zsh/z-a-submods

.gitmodules, install.conf.yaml
=> Use valid subdirectory for zinit

bin/upgrade
=> Change zplugin to zinit in bin/upgrade

bin/upgrade, install, vim/after/ftplugin/sh.vim
- installation
- upgrade
- enabling in VIM ftplugin
=> Adds bash-language-server

install.conf.yaml, zsh/zshrc
=> Finish migration to zinit from zplugin

.circleci/config.yml, .github/workflows/ci.yml, vim/editor.vim, vim/filetype.vim, vim/ftplugin/yaml.vim, vim/plugins.vim, vim/session.vim, vimrc
=> Lint vim configuration files

vim/plugins.vim, vim/session.vim
Previously I was using custom code but it seems like the plugin in
question does far better job.
=> Use farmergreg/vim-lastplace

install, pkg.install.conf.yaml
Fix for `ModuleNotFoundError: No module named 'distutils.core'`
=> Add python3-distutils

install
=> Modify paths to load envs for nvim pluign install

vim/editor.vim, vim/plugins.vim
- fzf
- vim-airline
- deoplete
=> No errors, initial load for several plugins

install
Detailed output does not help too much TBH.
=> Remove verbose flag

.gitmodules, config/terminator/config, pkg.install.conf.yaml, post-install
Having large repository is bad, let's see if this FiraCode that everyone says is nice will work nicely.
=> Use FiraCode from apt

.github/workflows/ci.yml
Ref: ab020c58943c9388e50ed3624022e4597427c02c
=> Install requirements to validate if there is no conflict
